// Generated by ModelEd

#define FRAME_start01	0
#define FRAME_attack001	1
#define FRAME_attack002	2
#define FRAME_attack003	3
#define FRAME_attack004	4
#define FRAME_attack005	5
#define FRAME_attack006	6

#define FRAME_attack007	7
#define FRAME_attack008	8
#define FRAME_attack009	9
#define FRAME_attack010	10

#define FRAME_attack011	11
#define FRAME_attack012	12
#define FRAME_attack013	13
#define FRAME_attack014	14
#define FRAME_attack015	15

#define MODEL_SCALE	1.000000 